### ISSUE TITLE
 How can I get a list of gRPC methods

### ISSUE THREAD

**Issue by xdorro** [bufbuild/connect-go#383] opened 2022-10-26 16:48 UTC
**Describe the solution you'd like**
I have 1 service as follows
```
service UserService {
  rpc FindAllUsers(FindAllUsersRequest) returns (FindAllUsersResponse) {}

  // Find User by ID
  rpc FindUserByID (CommonUUIDRequest) returns (User) {}

  // Create new User
  rpc CreateUser (CreateUserRequest) returns (CommonResponse) {}

  // Update User by ID
  rpc UpdateUser (UpdateUserRequest) returns (CommonResponse) {}

  // Delete User
  rpc DeleteUser (CommonUUIDRequest) returns (CommonResponse) {}
}
```
and I want to get the list of methods in that service like below
```
userServiceMethod := [
       "/user.v1.UserService/FindAllUsers",
	"/user.v1.UserService/FindUserByID",
	"/user.v1.UserService/CreateUser",
	"/user.v1.UserService/UpdateUser",
	"/user.v1.UserService/DeleteUser",
]
```

**Describe alternatives you've considered**
I have tried grpc-gateway and see they support this feature and hope connect-go support same feature too
```
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAllUsers",
			Handler:    _UserService_FindAllUsers_Handler,
		},
		{
			MethodName: "FindUserByID",
			Handler:    _UserService_FindUserByID_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user/v1/user.proto",
}
```

**Comment by mattrobenolt** [comment] 2022-10-26 17:01
I came up with a hack to accomplish this here: https://github.com/bufbuild/connect-go/issues/326#issuecomment-1189457172

It works well for our use cases in production.

**Comment by akshayjshah** [comment] 2022-10-26 17:03
Yep, this is a dupe of #326 - I'm going to merge it in there. I'm not opposed to exposing information like this somehow, but I'd like to get a little more context on what it needs to support beyond getting a list of methods.

**Closed by akshayjshah** 2022-10-26 17:03 UTC
Labels: duplicate

**Comment by joshcarp** [comment] 2022-10-26 17:31
So grpc/connect service/methods are implementations of the proto `service` construct and if you just need the method name you can get them from the `.pb.go` filedescriptor. 


```go
func TestFoo(t *testing.T) {
	methoddesc := pingv1.File_connect_ping_v1_ping_proto.Services().Get(0).Methods().Get(0)
	fmt.Println(FullMethod(methoddesc))
}

func FullMethod(c protoreflect.MethodDescriptor) string {
	return fmt.Sprintf("/%s/%s", c.Parent().FullName(), c.Name()) // prints /foo.ping.v1.PingService/Ping
}
```
