### ISSUE TITLE
Possible GRPC-Web incompatibility with grpc-dotnet

### ISSUE THREAD

**Issue by cchamplin** [bufbuild/connect-go#535] opened 2023-06-27 15:57 UTC
**Describe the bug**

When attempting to make GRPC-Web unary requests to Buf-Connect server implemented in Go from Kreya (https://kreya.app/) we receive the following error: "Error starting gRPC call. InvalidOperationException: Error parsing badly formatted trailing header."

We believe this is likely originating from the underlying GRPC library Kreya uses which is probably (https://github.com/grpc/grpc-dotnet/tree/master). The source of the error looks like it could be this line: https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.Net.Client.Web/Internal/GrpcWebResponseStream.cs#L241 

**To Reproduce**

Unfortunately we don't have a lot if ability to debug Kreya, but we are simply using a configuration that looks something like this:

![image](https://github.com/bufbuild/connect-go/assets/1944818/4fee06e8-eb51-4bdf-8d98-0d69811e01fd)

**Environment (please complete the following information):**
- `connect-go` v1.6.0
- `go version`: go version go1.20.5 darwin/arm64

**Additional context**
N/A

**Comment by bufdev** [comment] 2023-06-27 16:05
Is there any other information you can provide us to reproduce this? We'd be looking for a minimal and specific reproducible example.

**Comment by emcfarlane** [comment] 2023-06-27 19:53
It looks like an issue with Kreya.app handling compressed trailers. Tested it out locally with a simple service and it works when disabling compression (setting `Grpc-Accept-Encoding: identity`).

**Comment by akshayjshah** [comment] 2023-07-25 22:11
@cchamplin I'm going to close this, as it appears that the bug is in Kreya or one of its dependencies and there's a workaround available.

**Closed by akshayjshah** 2023-07-25 22:11 UTC
